allowBuilds:
  '@parcel/watcher': false
  edgedriver: false
  esbuild: false
  geckodriver: false
  lmdb: false
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - '@frankframework/doc-library-core'
  - '@frankframework/doc-library-ng'
