allowBuilds:
  '@parcel/watcher': false
  edgedriver: false
  esbuild: false
  geckodriver: false
  lmdb: false
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2200.5'
  - '@angular-devkit/core@22.0.5'
  - '@angular-devkit/schematics@22.0.5'
  - '@angular/cli@22.0.5'
  - '@schematics/angular@22.0.5'
  - '@angular/build@22.0.5'
  - '@frankframework/doc-library-core@1.0.5 || 1.0.6'
  - eslint-plugin-unicorn@70.0.0
